### ISSUE TITLE
Add-ons manager on Mac OS X

### ISSUE THREAD

**Issue by yozhic** [AddonLab/AiOS#105]
**Sorry**, **I was inattentive** and have not read the issue #102.

Since AiOS 0.7.28 I have problem with Add-ons manager opened in Tab. It has lost its original appearance and looks like in SideBar. And I can not find the option to return it back to the original. This problem did not exist in previous versions.

I am on the Mac OSX 10.8.5, Firefox 45.0.2 & AiOS 0.7.28.

![screencapture2016-04-27_10-14-30_am](https://cloud.githubusercontent.com/assets/13917732/14844491/6de28b02-0c60-11e6-8f06-9c3c6f0ceb0c.png)

**Comment by ingowennemaring** [comment]
Thanks for reporting, but I will close this issue due to the duplication of #102
