### ISSUE TITLE
Firefox 48.0a2 broke it

### ISSUE THREAD

**Issue by ccrowles** [AddonLab/AiOS#106]
Now it doesn't show the sidebar anymore, and if I click on addons it opens the sidebar in a new tab.

![screenshot03045](https://cloud.githubusercontent.com/assets/12866474/15013089/9996aa24-11fd-11e6-96a6-348279365824.jpg)

**Comment by ingowennemaring** [comment]
There will be an updated version very shortly.

**Comment by ingowennemaring** [comment]
Will be fixed in the next version 0.7.29 and will be released if it's approved by Mozilla.
