### ISSUE TITLE
"Open in Sidebar" Broken for All Panel Toolbar Buttons with Firefox Dev (48.0a2)

### ISSUE THREAD

**Issue by xeonx1** [AddonLab/AiOS#107]
## All Panels Now Failing to Open in Sidebar

The following toolbar buttons are now broken in this way (essentially all panels) disabled having Open in Sidebar enabled for each of them which had worked correctly before the the recent Firefox update:

1. Bookmarks
2. History
3. Addons
4. PageInfo
5. Multi Panel
6. Downloads
7. Error Console

## Screenshots for New Issue
As seen in the below screenshots, all AiOS toolbar buttons, now fail to result in any of those panels opening in the AiOS Sidebar. Instead, they open in a new small window, which appears different from the standard Bookmark Manager, etc. window - with the exception of Addon Manager when opens in a tab again.

![aios toolbar buttons open in sidebar broken](https://cloud.githubusercontent.com/assets/4053734/15156017/f60bae26-1699-11e6-8978-e4df0fbe5361.png)

All of these toolbar buttons worked fine and resulted in opening correctly in Sidebar up until a few days ago with the  recent Firefox update. 

As you can see, I have Open in Sidebar enabled under Options for each panel.

![aios settings for toolbar buttons open in sidebar broken](https://cloud.githubusercontent.com/assets/4053734/15156084/3dce0786-169a-11e6-983b-b6590b9ad4b6.png)

Firefox updates since then have not resolved the issue, so it seems that AiOS needs to be updated to maintain compatibility with Firefox Developer and Nightly editions and future Firefox stable updates.

## Others Reporting This Issue
It seems like Issue #106 reported only about the Addon panel no longer opening in the sidebar may be regarding the same issue.

## Limited Workaround
Only for Downloads and History, Ctrl+B and Ctrl+H do result in Bookmarks and History panels opening in the sidebar.
The associated Bookmarks and History menu items shown when clicking the drop-down at the top of the AiOS sidebar menu or the Sidebar Panels toolbar button likewise open in the sidebar.

I discovered there seem to be new "Bookmarks (Sidebar)" and "History (Sidebar)" toolbar buttons which seem to open in the sidebar. I would suggest that you restore the existing functionality for the previous AiOS bookmark and sidebar buttons instead of creating new buttons (instead of the half broken open small dialog window with sidebar like appearance), or rename display name (eg. instead of ID) of existing toolbar buttons and/or replace/upgrade existing buttons with the new ones, so as to avoid this appearing as broken to everyone and avoid having 3 sets of Bookmarks toolbar buttons.

However, as stated, the associated AiOS toolbar buttons for Bookmarks and History panels fail to do so, and none of the other hotkeys, like Ctrl+Shift+M for MultiPanel, open in Sidebar, and there are no new toolbar buttons available for them.

## My Configuration
AiOS  v0.7.28
Firefox Developer Edition (48.0a2) _64-bit build_
Windows 10 x64

**Comment by xeonx1** [comment]
@ingowennemaring 
Is this issue (as confirmed by issue reports from others as well, and seemingly affecting everyone using Firefox Dev or Nighty) something that could be fixed soon? If so, I would appreciate the help with it. Thanks.

**Comment by xeonx1** [comment]
@ingowennemaring

## Long-Standing Issue Applies to Many Major Versions
The Firefox update back in May (48.0a2) broke All-in-One Sidebar so that panels (Addons, Bookmarks, History, etc), so that toolbar buttons result in opening up a messed up version of the panel as a separate window (or in a tab, in the case of Addons).

This doesn't just apply to Nightly, it affects the pretty stable Dev Edition of Firefox as well, and has been consistently the case for many major versions now.

This is not some temporary Firefox issue, AiOS was broken when v48.0a2 was released, and it remains broken still several major versions later - with Firefox Dev now at 49.0a2 and Nightly at v50.0a1.

## Workaround
AiOS itself still seems to work OK and the panels can (if opened a certain way) show just fine in the sidebar (even with Dev Edition and beyond).
If you click on the AioS menu items (shown from AioS panel titlebar dropdown or shown as sub-items under the Sidebars > toolbar button which shows a menu). When selecting from there, Addons, Bookmarks, History, etc. open up on fine in AiOS sidebar.
Also, it seems like there might be another duplicate toolbar item that gets added (instead its one created from another addon for additional toolbar items) for Bookmarks and History (so I suggest testing with Addons instead), which result in the panels opening fine in the Sidebar, and the associated hotkeys (eg. Ctrl-B) work OK too.

## Proposed Quick Fix
Considering this, I'm hoping you could implement the fix pretty quickly, just by having the toolbar buttons work the same way - calling the same function as are called for the Sidebars menu items.
If you could do that, you might not even have to test with Dev Edition, etc. and it should work fine for Firefox Stable, Dev, and Nightly simultaneously

**Comment by paulthegreek2002** [comment]
um having the same problem to with all in one sidebar is there a fix for this please let me know

**Comment by ingowennemaring** [comment]
There will be an updated version very shortly.

**Comment by xeonx1** [comment]
Great, thanks.

**Comment by ingowennemaring** [comment]
Will be fixed in the next version 0.7.29 and will be released if it's approved by Mozilla.
