### ISSUE TITLE
sidebar tabs opens in new window

### ISSUE THREAD

**Issue by chezinut** [AddonLab/AiOS#109]
in latest version Firefox version 48 AiOS is buggy instead of sidebar downloads and others opens in new window

**Comment by dice1976** [comment]
I am seeing this too on FF 48.   I attempted to downgrade lower 2 versions and did not help

**Comment by InvictusX** [comment]
Yeah, 48 broke AiOS. Hope there will be an update soon, opening and closing windows all the time like a moron without the convenience of a *real* sidebar is a pain.  
Mozilla is doing their best once again...

**Comment by chezinut** [comment]
back to ff47.0.1 for me works :)

**Comment by cfoellmann** [comment]
How about we chip in and donate some money?
@ingowennemaring is the paypal donation via the mozilla addon website the right way to "pay" you?

**Comment by ingowennemaring** [comment]
There will be an updated version very shortly.

>  is the paypal donation via the mozilla addon website the right way to "pay" you?
Yes. :-)

**Comment by danowar2k** [comment]
Many thanks for fixing this. And here I thought my Firefox itself was broken.

**Comment by cfoellmann** [comment]
dear users of the AiOS,

if you like it and need AiOS as much as I do consider donating just a few bucks via Paypal: https://addons.mozilla.org/firefox/addon/all-in-one-sidebar/developers
I just "donated" $5 which is not much. just show @ingowennemaring that his work is appreciated.

**Comment by ingowennemaring** [comment]
Thank you very much. I really appreciate every support, no matter if it's a bug report or a donation.

**Comment by ingowennemaring** [comment]
Will be fixed in the next version 0.7.29 and will be released if it's approved by Mozilla.
