### ISSUE TITLE
I can't install new release 0.7.29

### ISSUE THREAD

**Issue by Strider1966** [AddonLab/AiOS#110]
Firefox 48 blocks the installation of AiOS 0.7.29 because the sign of the add-on is not verified.

I have tried to set the key  "xpinstall.signatures.required" to "false" but it does not work

How must I solve it? Thx :-)

**Comment by Clovis2** [comment]
I have the same problem

**Comment by ingowennemaring** [comment]
In the meantime the new version has been released and approved by Mozilla. Please try again to install it from the addons site: https://addons.mozilla.org/firefox/addon/all-in-one-sidebar/

**Comment by Strider1966** [comment]
Hi


after installation the situation seems to be worse than before. Now the sidebar of AiOS is zero width, the buttons have disappeared and if I click or if I try to enlarge it nothing happens!

Could you please help me? thx


________________________________
Da: Ingo Wennemaring <notifications@github.com>
Inviato: domenica 7 agosto 2016 19.24
A: AddonLab/AiOS
Cc: Strider1966; Author
Oggetto: Re: [AddonLab/AiOS] I can't install new release 0.7.29 (#110)


In the meantime the new version has been released and approved by Mozilla. Please try again to install it from the addons site: https://addons.mozilla.org/firefox/addon/all-in-one-sidebar/

[https://addons.cdn.mozilla.net/user-media/addon_icons/1/1027-64.png?modified=1470590417]<https://addons.mozilla.org/firefox/addon/all-in-one-sidebar/>

All-in-One Sidebar<https://addons.mozilla.org/firefox/addon/all-in-one-sidebar/>
addons.mozilla.org
AiOS lets you open various windows as sidebar panels, and quickly switch between them. So it put an end to the window chaos! In addition to bookmarks and history it opens dialogues such as downloads, add-ons and more in the sidebar.


-

**Comment by Clovis2** [comment]
Hi,
I have the same problem as Strider1966!
