### ISSUE TITLE
Thought it was just the Sidebar switch, addons and downloads not working, but...

### ISSUE THREAD

**Issue by Hellboy71** [AddonLab/AiOS#112]
Just went through absolutely everything on the view menu, to try and access AiOS and nothing comes up. Went to settings, I restored the defaults and restarted thinking than might help.  The most I can get to come up is the Toolbar, but that has to be done by selecting Toolbars -> AiOS.  Sending 2 pics, one is of the Toolbar, and the other is of the addons that I do have installed, I've seen people complaining about compatibility, just don't see how that would be the case.  But Hopefully this will help you out a little,  hope you can get this fixed, reasonably quickly.
![for github](https://cloud.githubusercontent.com/assets/8400916/17483812/8b481a86-5d55-11e6-83eb-211282b6f746.jpg)
![for github2](https://cloud.githubusercontent.com/assets/8400916/17483813/8b4cc2b6-5d55-11e6-9fe7-d01d31cba5f6.jpg)

**Comment by RDL-github** [comment]
>  @Hellboy71 

Did you try my suggestion about using the @Sidebar Grippy'?

https://github.com/AddonLab/AiOS/issues/111#issuecomment-238120817

(Posted in 'sidebar tabs do not open at all #111' )

By the way, how come you can post a picture of your extensions list displayed in the sidebar if AiOS isn't working?

Regards

RDL

**Comment by Hellboy71** [comment]
Ctrl+Shift+A or Tools then addons for addons, And yeah, I tried everything that's been suggested.

**Comment by Hellboy71** [comment]
Just tried a few things, was able to get it somewhat working. I did change the pixel size for min max, and standard, never had them above 300, 400, and 500 before, but no I do.  I'll up them again, if I can't get it working any better, quick enough.  In the General tap under Special I disabled, Enable Sidebar Collapsing.  Now I'm actually able to open things in the toolbar like I'm supposed to.  I just have to fine tune the clicks and presses to open it.  They are a bit screwy right now.  Give me a day or 2 and I'll be fine.  If not you'll hear from me again.....LOL

**Comment by pmruzicka** [comment]
I have the same problem with the sidebar. Can't find any way to get the mouse to respond to open the sidebar whether it is auto hidden or not. Tried most of the suggestions and am getting nowhere. So frustrating. I use this so much that when it goes down, it just drives me crazy...

**Comment by Hellboy71** [comment]
Using Ctrl or Shift does nothing?  Did you try what I just did?  I
restarted the browser afterwards.  And it's usually double clicking that
does anything.
Just a random thought, what version of Windows are you using, if at all?

**Comment by RDL-github** [comment]
Best Solution So Far for me:

1) Disable 'Sidebar Collapsing'
====================

and
===

2) Enable 'Sidebar Grippy' and, if necessary, use it
================================

See my previous post https://github.com/AddonLab/AiOS/issues/111#issuecomment-238770415 for details on method.

Regards

RDL

**Comment by pmruzicka** [comment]
Hellboy71 commented 9 hours ago
Using Ctrl or Shift does nothing?  Did you try what I just did?  I
restarted the browser afterwards.  And it's usually double clicking that
does anything.
Just a random thought, what version of Windows are you using, if at all?
_____________________
Yes, now got it working. Using Windows 10. Happier than a fly on s$%&!

**Comment by vobexo** [comment]
1) Disable 'Sidebar Collapsing'
and
2) Enable 'Sidebar Grippy' and, if necessary, use it

this works for me in 0.7.29

**Comment by ingowennemaring** [comment]
I will close this issue as duplicate from #111
