### ISSUE TITLE
New update changed the rules

### ISSUE THREAD

**Issue by gridflash** [AddonLab/AiOS#113]
AiOS no longer works. Clicking on the Sidebar tab turns the sidebar blue but nothing opens.

Is there a way to revert to the prior version?

**Comment by gridflash** [comment]
Okay you need to check off "Sidebar Grippy" in the View menu. Everything work as it was supposed to.

**Comment by astynax** [comment]
I checked off "Sidebar Grippy". Sidebar still doesn't open.

**Comment by imesg** [comment]
no workee for me.

**Comment by RDL-github** [comment]
AiOS 0.7.29 is an emergency release to avoid problems with Firefox 48.0.

It re-enables opening of panels in the sidebar, which is what AiOS is for.
However, for many users, there are some transient, but disconcerting, initial problems after updating to AiOS 0.7.29.

I believe that these may all be solved as follows.

1) Turn **off** AiOS Option 'Enable Sidebar Collapsing'

2) Enable 'Sidebar Grippy' in Firefox Menu > 'View'; then use it to open (and resize, if needed)  the sidebar

3) Enable 'Sidebar Switch' in Firefox Menu > 'View'; then use it to open the sidebar

For details on how to do those things;

a) Carefully read all of this existing bug report:

sidebar tabs do not open at all · Issue #111 · AddonLab/AiOS · GitHub

https://github.com/AddonLab/AiOS/issues/111

b) Go to the Author's Homepage (there is a link on the AiOS page on AMO
and read through the 'FAQ's and 'Features' sections (links in the top bar there). 

The screenshots there may also be helpful.

All-in-One Sidebar :: Sidebar Extension for Mozilla Firefox :: firefox.eXXile.net

http://firefox.exxile.net/aios/index.php


AiOS 0.7.29 re-enables opening of panels in the sidebar, which is what AiOS is for.
However, the emergency fix version no longer allows the features to instead open those panels in new windows or tabs. I hope Ingo will be able to restore those facilities when real life allows him time.

It is still possible to use the double headed arrow in the AiOS sidebar header to:

Open current sidebar content in a new window ( Shift+Click on double headed arrow )
Open current sidebar content in a new tab ( Ctrl+Click on double headed arrow )
Open current content area (webpage) display in the sidebar ( Click on double headed arrow )

**Comment by ingowennemaring** [comment]
Thanks @RDL-github! I will close this issue as a duplicate.
