### ISSUE TITLE
Middle click on toolbar buttons does not open their tabs anymore

### ISSUE THREAD

**Issue by githubusr0** [AddonLab/AiOS#115]
For example, addons or downloads buttons when middle-clicked used to open full sized tabs. It was very useful, depending on which purpose I'm pursuing, I used to click addons with left mouse click to enable or disable them quickly, and in other scenario I used middle click to open addons tab and customize options etc..

**Comment by RDL-github** [comment]
AiOS 0.7.29 is an emergency release to avoid problems with Firefox 48.0.

It re-enables opening of panels in the sidebar, which is what AiOS is for.
However, the emergency fix version no longer allows the features to instead open those panels in new windows or tabs. I hope Ingo will be able to restore those facilities when real life allows him time.

It is still possible to use the double headed arrow in the AiOS sidebar header to:

Open current sidebar content in a new window ( Shift+Click on double headed arrow )
Open current sidebar content in a new tab ( Ctrl+Click on double headed arrow )
Open current content area (webpage) display in the sidebar ( Click on double headed arrow )

For many users, there are also some transient, but disconcerting, initial problems after updating to AiOS 0.7.29.

I believe that these may all be solved as follows.

1) Turn **off** AiOS Option 'Enable Sidebar Collapsing'

2) Enable 'Sidebar Grippy' in Firefox Menu > 'View'; then use it to open (and resize, if needed)  the sidebar

3) Enable 'Sidebar Switch' in Firefox Menu > 'View'; then use it to open the sidebar

For details on how to do those things;

a) Carefully read all of this existing bug report:

sidebar tabs do not open at all · Issue #111 · AddonLab/AiOS · GitHub

https://github.com/AddonLab/AiOS/issues/111

b) Go to the Author's Homepage (there is a link on the AiOS page on AMO
and read through the 'FAQ's and 'Features' sections (links in the top bar there). 

The screenshots there may also be helpful.

All-in-One Sidebar :: Sidebar Extension for Mozilla Firefox :: firefox.eXXile.net

http://firefox.exxile.net/aios/index.php

**Comment by ingowennemaring** [comment]
Thanks @RDL-github! I will close this issue as a duplicate.

**Comment by RDL-github** [comment]
>  @ingowennemaring

> Thanks @RDL-github! I will close this issue as a duplicate.

I don't think this is a duplicate as it deals only with the withdrawal of the 'new page' and 'new tab' features, which I do not recall seeing mentioned in any other bug reports. Was it? If not, then it is a different problem from those. I realise that you did imply it in the version notes on AMO but I think that this user doesn't understand what that means. 

I've trimmed my reply to only address that problem, in case you feel my inclusion of extra, more general assistance just confused things.

VBRR
