### ISSUE TITLE
Latest Update Message stuck in Firefox.

### ISSUE THREAD

**Issue by Delboy666** [AddonLab/AiOS#116]
Ever since the latest update (0.7.29) Firefox opens a tab each time I run the browser telling me 'All-IN-One-Side-Bar' has been updated.
System reboots, Cache clear downs etc make no difference. Run firefox and up pops the 'Updated' message along with a request for donations.

**Comment by RDL-github** [comment]
>  @Delboy666 commented

> Ever since the latest update (0.7.29) Firefox opens a tab each time I run the browser telling me 'All-IN-One-Side-Bar' has been updated.

Please try this:

In your address bar/url bar/location bar (all same thing)

Type ':about config' (no quotes, but note the colon you need on the front)

If you get a warning to be careful, agree quietly (?OK or 'Yes I will be careful' or somesuch button?)

You'll see a window/tab listing Firefox preferences - yes, do be careful :D

Your cursor will be in a search/filter box

From here, copy the following (highlight it and press ctrl+C or whatever you normally use):

extensions.aios.changelog

Paste that into the about:config filter box.

You should now see only one line, for that entry, in the preferences list.

Double-click on that line.

You will see a box allowing you to change the value of that setting.

It probably says '0.7.28' (no quotes)

Change the value you see in that box to '**0.7.29**' (no quotes and you don't need to make it bold :D)

Press Enter.

Close that tab/window and restart Firefox.

Hopefully, the information page will be gone.


You may have other initial problems with AiOS 0.7.29. If so, please see other recent bug reports for possible solutions.

**Comment by Delboy666** [comment]
Thank you for your help. I have not tried this fix yet but am sure it will sort the problem.
Thanks again.
Del.

**Comment by RDL-github** [comment]
@Delboy666 

>Thank you for your help. I have not tried this fix yet but am sure it will sort the problem.

Hopefully, but only after you've corrected the erroreous line to:

>Type 'about:config' (no quotes, but note the colon)

Sorry the incorrect line got in there somehow.

Regards

RDL
