### ISSUE TITLE
AiOS will not open when toggled anymore! :(

### ISSUE THREAD

**Issue by klkquest** [AddonLab/AiOS#117]
The wonderful AiOS is there -- it turns blue like always -- but when clicked on will not open.  It has worked for years, now it doesn't work.  And only for moments today have I seen any of the little icons that link to i.e. the "star" for the bookmarks, or the "down-arrow" for your downloads.  What happened? You can see by the attached screen shot it is there -- and it turns blue when touched with the cursor -- but nothing happens any more -- nothing opens.  Can you help fix it please?  Thank you! 

![2016-08-10 all-in-one-sidebar not working](https://cloud.githubusercontent.com/assets/20960732/17577070/847aece4-5f2e-11e6-8345-4f610dfd7ea2.JPG)

**Comment by feeks** [comment]
I can confirm this for both ubuntu desktop 16.4 and Windows 10 x64

**Comment by Nightbr** [comment]
Same here. Thanks in advance for the fix

**Comment by Nightbr** [comment]
However, middle-click on the sidebar will open the toolbar. But I can't open bookmarks, history, ...

**Comment by RDL-github** [comment]
AiOS 0.7.29 is an emergency release to avoid problems with Firefox 48.0.

It re-enables opening of panels in the sidebar, which is what AiOS is for.
However, the emergency fix version no longer allows the features to instead open those panels in new windows or tabs. I hope Ingo will be able to restore those facilities when real life allows him time.

It is still possible to use the double headed arrow in the AiOS sidebar header to:

Open current sidebar content in a new window ( Shift+Click on double headed arrow )
Open current sidebar content in a new tab ( Ctrl+Click on double headed arrow )
Open current content area (webpage) display in the sidebar ( Click on double headed arrow )

For many users, there are also some transient, but disconcerting, initial problems after updating to AiOS 0.7.29.

I believe that these may all be solved as follows.

1) Turn **off** AiOS Option 'Enable Sidebar Collapsing'

2) Enable 'Sidebar Grippy' in Firefox Menu > 'View'; then use it to open (and resize, if needed)  the sidebar

3) Enable 'Sidebar Switch' in Firefox Menu > 'View'; then use it to open the sidebar

For details on how to do those things;

a) Carefully read all of this existing bug report:

sidebar tabs do not open at all · Issue #111 · AddonLab/AiOS · GitHub

https://github.com/AddonLab/AiOS/issues/111

b) Go to the Author's Homepage (there is a link on the AiOS page on AMO
and read through the 'FAQ's and 'Features' sections (links in the top bar there). 

The screenshots there may also be helpful.

All-in-One Sidebar :: Sidebar Extension for Mozilla Firefox :: firefox.eXXile.net

http://firefox.exxile.net/aios/index.php

**Comment by ingowennemaring** [comment]
Thanks @RDL-github! I will close this issue as a duplicate.
