### ISSUE TITLE
Bookmark search steals mouse focus on open

### ISSUE THREAD

**Issue by michaeldayla** [AddonLab/AiOS#119]
Since the latest upgrade, the bookmarks search filed in AiOS steals the focus of my mouse. So, if I begin to type without slicking on the search field in FF, I search my bookmarks. This was not the behavior before the recent upgrade. I am running Windows 7, FF 48.

**Comment by ingowennemaring** [comment]
This is not a change of AiOS and I can do nothing to change the behavior of the search field in the bookmarks sidebar.
