### ISSUE TITLE
Bookmark location always goes back to the top

### ISSUE THREAD

**Issue by bobbygithub66** [AddonLab/AiOS#129]
If I scroll down and select a bookmark and open it the side bar closes. When I reopen the sidebar the bookmark list isn't at the location where I just selected this bookmark. The list always goes back up to the top. This started last week sometime. I did not change any settings.

**Comment by Nikaas** [comment]
Have the same problem with Win10-x64, FF 48.0.2, AiOS 0.7.30

**Comment by ingowennemaring** [comment]
Closed as a duplicate from #120
