### ISSUE TITLE
"Show/hide Sidebar automatically" feature broken.

### ISSUE THREAD

**Issue by PPSaini** [AddonLab/AiOS#130]
Currently on Firefox 48.0.2 and using AiO Sidebar 0.7.30
I have always been able to use the "Show/hide Sidebar automatically (mouse contact instead of mouse click)" feature of AiO Sidebar without any issues, except for what seems to have started with the latest FF update.

This issue is not the same as the "unable to open sidebar" issue as I can open the sidebar manually. I have the "grippy" visible and I have "collapsing" disabled. I could not find a bug report concerning the automatic show/hide already submitted, so I created one. To be clear of the feature I am referring to I added a snippet of the options were it is enabled.
![menu_option](https://cloud.githubusercontent.com/assets/22125989/18415108/313a1994-779b-11e6-9b95-94f6b440d97e.PNG)

**Comment by indy259** [comment]
For me it seems to be dependant on which content is shown in the sidebar. If I have Bookmarks or History showing, the auto switch works fine. Otherwise it stays open. Looks like the latest FF update has broken a few features along with the sidebar swich / sidebar grippy confusion.

**Comment by Nikaas** [comment]
For me it doesn't work if the active "tab" is LastPass, for the rest (Bookmarks, History, etc.) it works.

**Comment by zbyna** [comment]
@Nikaas 
The same issue, TagSieve does not work.

**Comment by PPSaini** [comment]
Works with new update to 0.7.31. Awesome job 👍
