### ISSUE TITLE
Buttons in Page Information don't work anymore

### ISSUE THREAD

**Issue by swischniak** [AddonLab/AiOS#133]
All-in-One Sidebar 0.7.30
FF 48.0.2

Especially the button "show saved passwords" (Gespeicherte Passwörter anzeigen), which I frequently use bothers me. But it appears other button don't work either:
-show cookies
-show certificate
-no page info at all

**Comment by WiseLord** [comment]
The same with Fx-49

**Comment by buthub** [comment]
Yup, same here.  None of the Page Info buttons (except Help) are working.

Please at least restore the View Saved Passwords!  Thanks.

I'm on FF 50.1.0, with a bunch of add-ons, like Tab Mix Plus, Add Bookmark Here, Menu Wizard, NoScript, Organize Search Engines, Redirector, Session Manager, Zoom Page, etc.

**Comment by ingowennemaring** [comment]
The development of AiOS has been ended. Please take note of this message:
http://firefox.exxile.net/aios/end_of_development.php
