### ISSUE TITLE
[0.7.30] Font broken in Extensions tab after FF updated to ver. 49

### ISSUE THREAD

**Issue by mikolajek** [AddonLab/AiOS#137]
After I updated my Firefox to ver. 49 (and all consecutive ones), the font in the Extensions panel got bigger than the usual and no special or national characters are displayed anymore (see screenshot). The font in all other tabs stayed the same, so only Extensions tab seems to be affected. I haven't found any option to manipulate text in tabs, so I assume it's a bug...

![aios](https://cloud.githubusercontent.com/assets/3338580/19647774/fdef5bb2-99ff-11e6-94b1-94c34e1c405a.jpg)

**Comment by mikolajek** [comment]
Here's the Downloads tab preview to compare:
![aios2](https://cloud.githubusercontent.com/assets/3338580/19647806/28a9e6c4-9a00-11e6-9e86-caddf1d75146.jpg)

**Comment by Whisker72** [comment]
Hmmm... I did a rollback from 0.7.30 (and earlier 0.7.29) to 0.7.28 because of another issue (see #138), but I also have the problem with 0.7.28.

Can't say ATM if in this case AiOS alone is the culprit, though, because I'm using a number of other addons which could also be responsible for this (it **could** be possible that the addon Classic Theme Restorer could also have something to do with that (I remember faintly to have read something about that addon, but can't really remember right now if my memory is correct in that case right now).
Guess I'll play around deactivating other addons to isolate the problem in the next weeks and keep y'all posted here if I should learn something new and significant.

**Comment by ingowennemaring** [comment]
I'm not able to reproduce this issue. Most probably it's a compatibility problem with another extension or theme. Are you able to reproduce it with all other extensions disabled and using the standard theme?

**Comment by RDL-github** [comment]
@Whisker72  commented Oct 27, 2016
>..it could be possible that the addon Classic Theme Restorer could also have something to do with that..

I also saw this (or very similar) problem after updating tp FF49.0.2 and then CTR 1.5.8.1.

I noticed that **in CTR options**,

**Add-on manager > 'Alternative appearance'** was enabled. I don't believe I had chosen to enable that and, **when I disabled it, the problem went away**.

I have a lot of catching up to do at present, so won't stop to explore, but I suspect that CTR 1.5.8.1 is at the centre of this problem.

Regards

RDL

**Comment by Whisker72** [comment]
> I noticed that in **CTR options**,
> **Add-on manager > 'Alternative appearance'** was enabled. I don't believe I had chosen to enable
> that and, **when I disabled it, the problem went away**.
Aaaand Bob's your uncle!
Checked it too, and it was exaclty the same. You can even watch the font change when having the addon-tab and the CTR options (I'm also using CTR 1.5.8.1) open and toggling the option.

@mikolajek, your first screenshot doesn't show if you're using the Classic Theme Restorer addon. So if you have it installed, it might help if you try the solution from RDL-github and tell us what happens.

**Comment by mikolajek** [comment]
Yes, you're totally right about the "Alternative appearance" option, RDL-github! Thank you for this suggestion!

I disabled it and my list is ALMOST back to normal - I'm saying "almost" as the font size is now correct but the "bush characters" are still present there... :(

**Comment by mikolajek** [comment]
OK, strangely enough the font encoding issue seems to have been linked to the certificate I have installed in my FF. I've just updated it as a part of regular maintenance and the fonts are now presented in a correct way...
