### ISSUE TITLE
0.7.31 won't install in FF 49.0.2

### ISSUE THREAD

**Issue by bobf32** [AddonLab/AiOS#139]
FF notices there's an update available and I do an update from within the panel displayed by AiOS. Restart FF and when back up I am still on 0.7.30. 

If I try install from http://firefox.exxile.net/aios/changelog.php I get warning message, select the Allow button only to be told FF has prevented this site from installing an unverified add on.

**Comment by ingowennemaring** [comment]
Please install the version from the official site at Mozilla: https://addons.mozilla.org/firefox/addon/all-in-one-sidebar/

The version on my homepage isn't verified by Mozilla and only for testing purposes. But maybe I should write exactly that on my site. ;-)

**Comment by bobf32** [comment]
Thanks. I think the reason it didn't install from properly the first time was a red herring.
