### ISSUE TITLE
bookmarks toolbar suddenly stopped working.

### ISSUE THREAD

**Issue by othereyes111** [AddonLab/AiOS#141]
my bookmarks toolbar has suddenly stopped working. the toolbar shows up in the proper place, but it is blank with no entries in it. The "bookmark toolbar" folder still appears in the sidebar bookmark panel with all the links intact, but none of them show up in the toolbar.
I have tried to drag the links onto the toolbar but this does nothing.
other buttons are behaving erratically as well, they will work but they do not seem as fluid as they were before. they seem more temperamental.
I believe that I have the latest versions of AiOS and firefox and the Mac OS.

**Comment by RDL-github** [comment]
@othereyes111 commented 10 hours ago

>my bookmarks **toolbar** has suddenly stopped working. the toolbar shows up in the proper place, but it is blank with no entries in it. The "bookmark toolbar" folder still appears in the sidebar bookmark panel with all the links intact, but none of them show up in the toolbar.
I have tried to drag the links onto the toolbar but this does nothing.
other buttons are behaving erratically as well, they will work but they do not seem as fluid as they were before. they seem more temperamental.
I believe that I have the latest versions of AiOS and firefox and the Mac OS.

This does not seem to have anything to do with the 'All-in-One **Sidebar**' extension.

It seems likely that you have just (been) updated to Firefox 50 and one or more of your installed extensions are no longer compatible/usable. Please make sure all your extensions are up-to-date.

If that does not solve your problem, please take it to the following user-driven forum where a wide class of Firefox questions are considered. Start a new topic/thread there and, in your initial problem description there, you should include exact information on your operating system name and version and your Firefox version (an example would be Win 10 x64, Firefox 50.0 x64).

Include MAC in the subject/title of your topic. That may help to alert respondents with MAC experience.

Firefox Support • mozillaZine Forums

http://forums.mozillazine.org/viewforum.php?f=38


NB that forum is run by volunteer experienced Mozilla users: it is NOT run by Mozilla.

**Comment by ingowennemaring** [comment]
The development of AiOS has been ended. Please take note of this message:
http://firefox.exxile.net/aios/end_of_development.php
