### ISSUE TITLE
AIOS has been updated webpage comes up every launch of firefox

### ISSUE THREAD

**Issue by SPMelly** [AddonLab/AiOS#142]
Even after i followed the steps listed in your FAQ

**Comment by RDL-github** [comment]
@SPMelly 
> Even after i followed the steps listed in your FAQ

Didn't see your specific problem in FAQs but does the following link help?

Latest Update Message stuck in Firefox. · Issue #116 · AddonLab/AiOS

https://github.com/AddonLab/AiOS/issues/116

**Comment by ingowennemaring** [comment]
The development of AiOS has been ended. Please take note of this message:
http://firefox.exxile.net/aios/end_of_development.php
