### ISSUE TITLE
Thumbnails of Open Tabs Not Dosplaying Correctly after Updating to Firefox 53.0

### ISSUE THREAD

**Issue by jmkiska** [AddonLab/AiOS#152]
Since updating to version 53.0 of Firefox the thumbnails of open tabs are not displaying correctly in the sidebar.  See below:

![image](https://cloud.githubusercontent.com/assets/25555316/25480774/42d4948c-2b18-11e7-926f-d8a0664c5113.png)

Some of the thumbnails are wider than others causing the "Close Box" to be hidden.  I have tried to adjust the setting but nothing seems to help.

I'm running OS X 10.11.6, Firefox 53.0 and AiOS 0.7.31

**Comment by vrubleg** [comment]
AFAIK, All-in-One Sidebar doesn't have this feature. So, you're using some additional extension for it.

**Comment by ingowennemaring** [comment]
That's correct, it's not a bug of AiOS, but most probably of the third-party extension.

However, the development of AiOS has been ended. Please take note of this message:
http://firefox.exxile.net/aios/end_of_development.php
