### ISSUE TITLE
Pale Moon Support

### ISSUE THREAD

**Issue by FranklinDM** [AddonLab/AiOS#153]
Are there any plans of officially supporting Pale Moon?

**Comment by fofajardo** [comment]
After reading the discontinued notice, I just decided to fork this extension for PM.
The new repository is up [here](https://github.com/FranklinDM/TGS) as The Good 'ol Sidebar.

**Comment by ingowennemaring** [comment]
That's fantastic! Good to see that it's alive. :)

**Comment by fofajardo** [comment]
@ingowennemaring Hi, I just wanted to ask something about the translations. Is it fine if I re-upload these at BabelZilla?
