### ISSUE TITLE
[Website] "Report Bugs" Links to Dead Forums instead of GitHub Issues

### ISSUE THREAD

**Issue by PowerAccess** [AddonLab/AiOS#154]
The All-in-One Sidebar website's [Issues page](http://firefox.exxile.net/aios/knownissues.php) has a link for Report Bugs which has a link to non-existent forums page:
http://firefox.exxile.net/forum_new/viewforum.php?f=2

This should instead be changed to link to the following URL for this GitHub project Issues page: 
https://github.com/AddonLab/AiOS/issues
Also, having a prominent link to this GitHub project page such as https://github.com/AddonLab/AiOS - possibly named [Latest Source](https://github.com/AddonLab/AiOS) under the "Install / Download" website sidebar panel - could be useful.

![image](https://user-images.githubusercontent.com/4053734/27301868-a051c22e-54e9-11e7-8f9e-5ccd8bc1dd9f.png)

**Comment by ingowennemaring** [comment]
The development of AiOS has been ended. Please take note of this message:
http://firefox.exxile.net/aios/end_of_development.php
