### ISSUE TITLE
AIO Sidebar Disappeared

### ISSUE THREAD

**Issue by SergeGardien** [AddonLab/AiOS#156]
Right out of the blue my AIO sidebar disappeared.
I'm on a Mac OS X 10.11.6, Firefox 54.0.1 and AIO Sidebar 0.7.31
I haven't added any new addon and till now everything was working fine.

Do you know of any issues with this configuration?

**Comment by JuPlutonic** [comment]
The same here (like out of the blue) 54.0 (64 bit) 54.0+build3-0ubuntu0.16.04.1 AIO Sidebar 0.7.31.1 disappeared!
Its a nightmare! When I install the addon from addons.mozilla.org and restart browser nothing happens: AIO absent in addons list
PS: Where I can find dev version of AIO? I will try reapply d095540 (.zip unpak, make zip inside directory where is all unpacked staff and rename zip to apk) but code in d095540 is too old...

**Comment by JuPlutonic** [comment]
the same here: d095540 / 0.7.31 http://i.imgur.com/uK9bg72.png disappears after install and restart

**Comment by JuPlutonic** [comment]
the same here: d095540 / 0.7.31 `http://i.imgur.com/uK9bg72.png` disappears after install and restart
afterwards `http://i.imgur.com/8a8WKPA.png` I removed `rem` ana `rem' here/ What is it ?!

**Comment by JuPlutonic** [comment]
[pic](http://i.imgur.com/uK9bg72.png)
[pic](http://i.imgur.com/8a8WKPA.png) these two fields are with `rem` value. Wtf!?
Happens when I'm trying to install 0.7.31. After installation I make restart and the addon disappears.

**Comment by SergeGardien** [comment]
I've done an AIO setting reset and now it is fine in my case.

**Comment by JuPlutonic** [comment]
About:Config `browser.uiCustomization.state` is a reason I removed from that field's value:
`"aios-toolbar":["toggle-button--jid1-qofqdk4qzufgwqjetpack-configure-for-current-tab-button","ublock0-button","customizableui-special-separator337","home-button","customizableui-special-separator1","privateTab-toolbar-openNewPrivateTab","customizableui-special-separator2","dta-manager-button","unplug2_toolbarbutton","tb-chatzilla-open","customizableui-special-separator338","bookmarks-button","history-button","onotesButton","downloads-button","addons-button","multipanel-button","tools-updatescan-button","pageinfo-button"],"aios-sbhtoolbar":["autohide-button","paneltab-button","sidebarclose-button"]`
and finnaly  `"dirtyAreaCache": [... ,"aios-toolbar" ...   ... ,"aios-sbhtoolbar" ...]`

**Comment by JuPlutonic** [comment]
No SergeGardien, I cleaned about:config (aois browserstate etc) and restarted and tried to reinstall 0.7.31/0.7.31.1 ... wasted ...

**Comment by JuPlutonic** [comment]
**FF 55.0.2+build1-0ubuntu0.16.04.1 0.7.31.1**  - close issue
settings including browser state ui(Personalized set of instrument icons) are back

**Comment by ingowennemaring** [comment]
The development of AiOS has been ended. Please take note of this message:
http://firefox.exxile.net/aios/end_of_development.php
