### ISSUE TITLE
Move AiOS to waterfox add-on store

### ISSUE THREAD

**Issue by mozillahatesprivacy** [AddonLab/AiOS#157]
Waterfox[1] is a firefox version with the stupid from mozilla removed and tries to give users what they want, main features are:

    Disabled Encrypted Media Extensions (EME)
    Disabled Web Runtime (deprecated as of 2015)
    Removed Pocket
    Removed Telemetry
    Removed data collection
    Removed startup profiling
    Allow running of all 64-Bit NPAPI plugins
    Allow running of unsigned extensions
    Removal of Sponsored Tiles on New Tab Page
    Addition of Duplicate Tab option
    Locale selector in about:preferences > General

The recent release of waterfox 55 introduces the first change for continued legacy add-on support[2], in the next few weeks waterfox will have its own add-on store to host those addons. It would be nice to have AiOS on this store. Even if development has stopped, AiOS is a terrific and very useful addon, it would be better to have it there than having it disappear.

[1]: https://www.waterfoxproject.org/blog/
[2]: https://technewsblogs.com/news/waterfox-55-news-android-app-continued-legacy-add-on-support/

**Comment by ingowennemaring** [comment]
I will not do anything about this, but the extension will not disappear. It's still on the Firefox add-ons page and last but not least on my own page: http://firefox.exxile.net/.
