### ISSUE TITLE
low: update "Releases" in the github repo

### ISSUE THREAD

**Issue by JuPlutonic** [AddonLab/AiOS#158]
In Releases last is
v0.7.31 …      d095540 
but in addons.mozilla.org last is v0.7.31.1
I don't, actually, know what commit used for new version on mozilla

**Comment by ingowennemaring** [comment]
The development of AiOS has been ended. Please take note of this message:
http://firefox.exxile.net/aios/end_of_development.php

Version 0.7.31.1 is technically identical with 0.7.31. I released it to make sure, that every user is informed about the end of life of this extension. A new version number opens a popup window containing the release notes.
