### ISSUE TITLE
Add-on SDK Color picker does not work in AiOS

### ISSUE THREAD

**Issue by MarkaPola** [AddonLab/AiOS#19]
Hi,

Add-on [Linkificator](https://addons.mozilla.org/en-US/firefox/addon/linkificator/?src=ss), based on [Add-on SDK](https://addons.mozilla.org/en-US/developers/docs/sdk/latest/dev-guide/index.html), is relying on color pickers for some functionality.
Unfortunately, when used in the sidebar managed by AiOS, color pickers are not longer usable : clicking on the color pickers does not do anything.

Thank you for your help.

MarkaPola

**Comment by ingowennemaring** [comment]
It's fixed in an unspecified release of Firefox in the past.
