### ISSUE TITLE
AiOS Toolbar Icons Appearing In "Findbar Tweak" Window

### ISSUE THREAD

**Issue by KhunRoger** [AddonLab/AiOS#30]
I made this comment on "Findbar Tweak" at GitHub:

"I have the FindBar at the bottom of the page.
I have the All-In-One Sidebar add-on installed (AiOS).
On the left of my screen is the AiOS Toolbar.
It's icons are appearing on top of the FindBar.
I believe the FindBar should not overwrite the AiOS Toolbar."

Here:
https://github.com/Quicksaver/FindBar-Tweak/issues/117#issuecomment-35153015 

The response from Findbar Tweak starts:

"Actually, FBT isn't overlapping anything. It's cutting the window off. It's the AiOS's toolbar fault for showing overflown icons, and it doesn't do it with every one of them either from my tests."

So there is a problem somewhere with the windows / icons. 
Here is an example of what I see when the Findbar window appears at the bottom of the screen and the AIOS toolbar icons appear on top of the Findbar window:

![findbar aios toolbar clash](https://f.cloud.github.com/assets/6468036/2178113/008b3840-9658-11e3-8568-254b102d5265.jpg)

**Comment by ingowennemaring** [comment]
In some way it seems to be fixed, because I'm not able to reproduce it.
