### ISSUE TITLE
Not compatible with Hide Menubar addon, breaks bookmarks toolbar

### ISSUE THREAD

**Issue by sailfast88** [AddonLab/AiOS#39]
AiOS breaks the bookmarks toolbar when used on FF29.0 in conjunction with Hide Menubar 6.0.20110915.  The bookmarks toolbar shows up as empty.  I have disabled and reenabled my add-ons one by one in order to locate the problem, and the conflict is definitely between hide menubar and AiOS.
![addons problems](https://cloud.githubusercontent.com/assets/7488898/2878408/969357f4-d45c-11e3-846c-2f5d0fb8cf2e.png)

**Comment by derkopfschuettler** [comment]
I have the same problem with the CsFire 1.08 Add-on. When it is activated it breaks the bookmarks toolbar too.
I examined it the same way as described by sailfast88.
My AiOS Verson is 0.7.25

**Comment by ingowennemaring** [comment]
Hide Menubar hasn't been updated for more than 4 years and CsFire for more than 3 years. I'm sorry, but I can't guarantee compatibility with obviously dead extensions.
