### ISSUE TITLE
Downloads button doesn't work in Australis (>=29.0.0)

### ISSUE THREAD

**Issue by wolfield** [AddonLab/AiOS#42]
Instead of opening actual sidebar it opens a drop-down tooltip:

![12](https://cloud.githubusercontent.com/assets/7544436/2939040/08f87588-d933-11e3-81cd-6bfd049f8d5c.png)

And for some reason the button used for downloads is a FF built-in one, while other buttons are custom. 
So I guess AiOS just lacks one another custom button for downloads.
Downloads sidebar works as expected if you are opening it through menu in AiOS button.

**Comment by ingowennemaring** [comment]
In the meantime I checked it again and again and I'm not able to reproduce such a problem.
