### ISSUE TITLE
remember clicked bookmark and scroll position after changing panel

### ISSUE THREAD

**Issue by Jan02** [AddonLab/AiOS#62]
remember clicked bookmark and scroll position after changing panel

position is forgotten when switching between panels.

aios 0.7.24
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:32.0) Gecko/20100101 Firefox/32.0

**Comment by ingowennemaring** [comment]
This can't be done by AiOS. It would be a nice request for the Firefox developers.
