### ISSUE TITLE
Toolbar is not visible on setup toolbar page ("Classic theme")

### ISSUE THREAD

**Issue by ms-sousuke** [AddonLab/AiOS#65]
Hello. After updating firefox to v32 (from v28) and installing "Classic Theme Restorer", there is no option to change items/icons on AiOS sidebar. The sidebar is not visible on setup page. Adding screens.
Regars
MS.

P.S: Huge thanks for great work.

![aios1](https://cloud.githubusercontent.com/assets/9250486/4644699/cdebf9e0-545e-11e4-9eba-f9afd873c5ea.png)
![aios2](https://cloud.githubusercontent.com/assets/9250486/4644700/cdf195da-545e-11e4-8a65-bed5b5dcb686.png)

**Comment by ingowennemaring** [comment]
It's not reproducible in later versions of Firefox and the addon.
