### ISSUE TITLE
AiOS doesnt seem to play well with Status4Evar and The AddOn Bar Restored extensions.

### ISSUE THREAD

**Issue by venterlin** [AddonLab/AiOS#66]
When I have AiOS enabled, my status bar does not appear in the latest Firefox, either when first starting, or restarting firefox. I have to resize the window to make the status bar appear. This happens with both the "Status4Evar" and "The AddOn Bar Restored" addons. 

Could this be fixed with AiOS or do you feel it's an issue with the other aforementioned addons.

Thanks for any response.

Love this add-on, would be lost without it!

**Comment by ingowennemaring** [comment]
The problem isn't reproducible.
