### ISSUE TITLE
Request - make it compatible with "Flash Control" addon

### ISSUE THREAD

**Issue by LL25255252** [AddonLab/AiOS#67]
The "Flash Control" addon has a sidebar UI (used to manage its whitelist).
When having both AIOS and Flash Control the "flash Control" sidebar can't be reached in any way.

Many thanks in advance.

Firefox 33
Win 7 x64

**Comment by ingowennemaring** [comment]
It's possible to open the config panel via the plugin button in the toolbar and the menu View > Sidebar > Flash Control.
