### ISSUE TITLE
Firefox 29: How can I add/remove other buttons to/from the AiOS toolbar?

### ISSUE THREAD

**Issue by Urhixidur** [AddonLab/AiOS#68]
The standard FAQ answer is: Right-click on the AiOS-Toolbar and choose Customize... Just drag and drop items from the customization window to the toolbar or vice versa.

However, with Firefox 29 the AiOS-Toolbar disappears as soon as you enter customization mode.  How can it be kept customizable?

**Comment by ingowennemaring** [comment]
The AiOS Toolbar just appear inside the customizing window in vertical mode right under the navigation toolbar.

**Comment by Urhixidur** [comment]
I had completely lost it from view.

**Comment by ingowennemaring** [comment]
I'm sorry for the very late answer, but do you mean that the problem has been solved for you or you just don't use AiOS anymore?

**Comment by Urhixidur** [comment]
No, I mean the AiOS toolbar is very discreet in customizing mode; since it is unexpected for it to move to the top, it had escaped my notice.

**Comment by ingowennemaring** [comment]
Okay, nice to know that it works for you. :-)

**Comment by ingowennemaring** [comment]
https://www.youtube.com/watch?v=WoW1P7hCKVI



Am 17. Juli 2015 bei 22:31:17, Daniel U. Thibault (notifications@github.com) schrieb:

No, I mean the AiOS toolbar is very discreet in customizing mode; since it is unexpected for it to move to the top, it had escaped my notice.
