### ISSUE TITLE
Can't restore sidebar header controls

### ISSUE THREAD

**Issue by bsassone** [AddonLab/AiOS#69]
Hi, 

I had to go back to defaults in my firefox customization and now I've lost the sidebar header controls and don't know how to get them back.

![capture](https://cloud.githubusercontent.com/assets/3892705/5303874/2db8f7aa-7ba2-11e4-8ecc-ff953e52d564.PNG)

I've done this before, but now it doesn't seem to be working. If I right click on the header, nothing happens. If I goto customize, there used to be another 'toolbar' under the aios one, but now its gone with no way to get it back.

![capture2](https://cloud.githubusercontent.com/assets/3892705/5303917/901f7220-7ba2-11e4-8976-041a8a869daf.PNG)

The reason I had to reset to defaults was because I added one too many spaces to the aios toolbar, then couldn't remove them! I could select anything else I add there, but spaces won't drag out.

**Comment by ingowennemaring** [comment]
Please check inside the customizing window ("Show / Hide Toolbars" button at the bottom of the window), wether the Sidebarheader Toolbar is enabled.
