### ISSUE TITLE
Sidebar becomes a more visual white stripe in full screen mode.

### ISSUE THREAD

**Issue by Skogmann** [AddonLab/AiOS#73]
is:issue is:open Sidebar becomes a more visual white stripe in full screen mode. Top, bottom and right screen edge hasn't the white stripe. The white stripe is the "Show/hide-sidebar-mouse-contact function. Latest FF and AiOS.

**Comment by Jorlem** [comment]
This just got rather more annoying, as with the latest Youtube update*, there is now a white stripe on the left edge of my screen whenever I make a Youtube video fullscreen.

*Youtube now uses HTML5 as the default, so fullscreen is now the browser fullscreen, instead of opening a new Flash window.
