### ISSUE TITLE
AiOS takes focus from URL bar to bookmark search

### ISSUE THREAD

**Issue by CreamyCookie** [AddonLab/AiOS#74]
I understand that some may like this, but for me 99 % of times when I open a new tab I want to type in the URL bar and not search in my bookmarks. So, if this isn't a bug, please add an option in the preferences to disable focus grabbing.

**Comment by ingowennemaring** [comment]
@CreamyCookie : I can't reproduce this problem. Are you able to reproduce it with the latest version of Firefox?
