### ISSUE TITLE
Issues with Themes

### ISSUE THREAD

**Issue by Evil-Ash** [AddonLab/AiOS#77]
![aios-theme](https://cloud.githubusercontent.com/assets/7687566/7303913/0c922e32-e9f4-11e4-866e-ed1e9b6e9165.png)

To reproduce: Firefox 37.0.2 new profile with AIOS 0.7.25
Change the default Fx theme to anything else (I used "Space Fantasy".). The theme is not displayed correctly.

**Comment by ingowennemaring** [comment]
@Evil-Ash : Sorry, such problems are not an issue of AiOS, but of the themes.
