### ISSUE TITLE
Firefox 40 new addons page issue

### ISSUE THREAD

**Issue by LonMcGregor** [AddonLab/AiOS#78]
There is an issue with displaying the new addons page that was introduced in firefox 40 in the sidebar. There is a lot of padding on this page and it makes it quite hard to navigate properly.

**Comment by yetanotheraccountname** [comment]
This is also afflicting the about:addons page itself, the horizontal navigation bar from the AiOS addon panel is also displayed there, including the padding.

![clipboard02](https://cloud.githubusercontent.com/assets/8466953/7802327/82f8effe-0333-11e5-8b53-c94959986cf9.png)

.
