### ISSUE TITLE
The buttons are hidden, seemingly permanently

### ISSUE THREAD

**Issue by TheZnayx** [AddonLab/AiOS#80]
The sidebar buttons are hidden, no matter what I try. The sidebar is still technically functional. When I click the minimize/maximize bar to open and close it, it opens and closes the sidebar at where I opened it last. However, the buttons are hidden, so I need to go through Firefox's default menu buttons (upper right corner) to show the different sidebar sections. I've tried the following:

1.  Searching in Firefox menus, repetitively closing and opening it through different methods (no, not enough to make it buggy or lagging - just enough to test if all it needed was some prods to work again)
2. Restarting Firefox
3. Restarting my computer
4. Disabling and re-enabling the add-on
5. Removing and reinstalling the add-on
6. Researching other solutions on the Net

None of my fixing attempts worked. It functioned perfectly just earlier today. Please try to help, and thank you.

**Comment by ingowennemaring** [comment]
@TheZnayx : You could try to restore the defaults inside the customizing window. Or disable other extensions to check for an incompatibility.
