### ISSUE TITLE
Cannot resize sidebar with custom firefox themes (other than "Default")

### ISSUE THREAD

**Issue by bwegge** [AddonLab/AiOS#85]
When using a custom Firefox theme (from https://addons.mozilla.org/en-US/firefox/themes/) instead of the "Default", the sidebar cannot be resized anymore. The small strip between sidebar and main browser content area where the mouse cursor is expected to change to the "horizontal resize arrows" seems to disappear/shrink to 0 pixels width and hence is not available.
It was reproducible with all themes I tried so far (e.g. https://addons.mozilla.org/en-US/firefox/addon/dark-fox-18066/). Reverting to the built-in "Default" theme makes the resize strip reappear and resizing works again.

**Comment by ingowennemaring** [comment]
Sorry, but it's not reproducible for me. And it doesn't sound very logical, because such themes are only define new colors and a backgound image. They do not change gui elements like resizers.

Are you able to reproduce it with all other extensions disabled and Dark Fox enabled?
