### ISSUE TITLE
Other sidebars affected on AiOS expand/minimise

### ISSUE THREAD

**Issue by stilez** [AddonLab/AiOS#87]
I'm using a vertical tab extension (Vertical tabs (simplified)) and AiOS.
When AiOS expands, the vertical tab bar is shrunk and it shouldn't be.

What I mean by this is, say I have a side tab bar 500px wide. When AiOS sidebar expands to say 300px, my tab bar gets shrunk to 200px, instead of staying the same size. Not sure if this is an AiOS issue or something else but seems to only be an issue with AiOS.

**Comment by ingowennemaring** [comment]
This isn't an issue of AiOS and it can't be fixed by me.
