### ISSUE TITLE
back-forward buttons keep disappearing? 

### ISSUE THREAD

**Issue by ksdixon** [AddonLab/AiOS#88]
The back/forward buttons that appear on the sidebar next to the 'check for updates' button and the search box, have started appearing and disappearing at random. I am not sure what causes this. Can anyone shed any insight?

**Comment by ksdixon** [comment]
An example of when AIOS back/fwd buttons disappear: When clicking 'More Infromation' on the addons ppanel. Instead of being able to press back to go back to the main list of addons, now I must click a different AIOS button, like downloads, and then click back to addons.

In FF35 a fool proof fix was for me ot roll-back to AIOS version 0.7.25.1; however doing this does not work in FF40; where the back/fwd buttons never actually appear anymore.

**Comment by ksdixon** [comment]
FF42 / Latest AIOS build = not fixed.
For now I am stuck back on FF35 & AIOS 0.7.25.1 if I want back and forward buttons to appear and work normally.

Is there any update with this? Some code must have changed in the addon after 0.7.25.1 in order to affect the back/forward buttons.

**Comment by ingowennemaring** [comment]
There are no more back/forward buttons in the addon panel in current versions of Firefox. They were removed by Mozilla.
