### ISSUE TITLE
0.7.27 Does not fix #82 for me.

### ISSUE THREAD

**Issue by RDL-github** [AddonLab/AiOS#90]
Thanks for latest release (0.7.27). Unfortunately, it does not solve this problem for me so I have retained the CSS which I used to circumvent the problem before.

Please note, in case it might be relevant, that although I am using Win 7 x64 and have a 4 core processor, I am using FF41.0.1 which does not officially support multiprocessing.

VBRR.

**Comment by ingowennemaring** [comment]
Let's track this bug still at #82.
