### ISSUE TITLE
Sidebar not appearing

### ISSUE THREAD

**Issue by freezecook** [AddonLab/AiOS#91]
The sidebar stopped appearing, and I haven't been able to get it back. It's not even collapsed, it's just not appearing at all.

**Comment by freezecook** [comment]
Update: I was able to get it to return using hotkeys. Still an odd behavior; I think Firefox went fullscreen before the problem happened.

**Comment by hixe33** [comment]
Same problem here. Works with the hotkeys too.

**Comment by ingowennemaring** [comment]
So, what's exactly the problem? It appears when using hotkeys, but not when.... ?

**Comment by hixe33** [comment]
The bar did not appear the rest of the time.
But now, for a mysterious reason, I don't have the bug anymore.
