### ISSUE TITLE
Doesn't play well with Minimap-Scroller addon

### ISSUE THREAD

**Issue by edouard-lopez** [AddonLab/AiOS#92]
Closing All-in-One Sidebar make [minimap scroller](https://github.com/diox/firefox-minimap-scroller) disappear.

see [diox/firefox-minimap-scroller/issues/17](https://github.com/diox/firefox-minimap-scroller/issues/17).

**Comment by ingowennemaring** [comment]
I can't get the extension to work and it seems that the development of Minimap Scroller Sidebar has been stopped long time ago. Additionally the extension doesn't use the default Firefox sidebar api. So it seems to me, that nothing will be changed here.
