### ISSUE TITLE
After update Mozilla 42 no information display about site in All in one side bar

### ISSUE THREAD

**Issue by capogr** [AddonLab/AiOS#95]
![untitled-1](https://cloud.githubusercontent.com/assets/3410222/11662393/0c675992-9ddf-11e5-9063-221e7ab57493.jpg)
After i updated to Mozilla 42 the info button does not display information about the site.

**Comment by RDL-github** [comment]
**@capogr**: this problem has already been reported. Please see existing bug reports

"aios not compatible with "page info" #94" and
"Page Info / Security is empty #93"

**Comment by ingowennemaring** [comment]
I will close this issue due to the duplication.
