### ISSUE TITLE
[Feature Request] Include Vertical tabs in AiOS

### ISSUE THREAD

**Issue by blausand** [AddonLab/AiOS#96]
I would really love the TreeStyleTabs be the "default" content of the AiOS.
I guess this would imply work on both sides, right?
Then my request would be: please describe what has to be done to make that possible, having the tabs in your SideBar.

Thank you!!

**Comment by kingtosh** [comment]
you had better to use "Pano". It has perfect compatibility to Aios.

**Comment by blausand** [comment]
I tried Pano and compared it to Tree Style Tabs. I liked that Pano shares the
native groups.
But since Tree Style Tabs are more responsive and less ressource hungry, i
requested the developer of Tree Style Tabs to copy that behaviour.
Since native groups are to die, the topic has to be rediscussed, however.

**Comment by kingtosh** [comment]
had you tried to use "unified sidebar" with "tree style tabs"?
there is a little bit of problems, but I could use "tree style tabs" with Aios.

OR, how about "tab tree"?

**Comment by blausand** [comment]
Tree Style Tab actually works fine beside AIOS. It's just that i can't choose to move the tree of tabs _inside_ the AiOS

**Comment by ingowennemaring** [comment]
The intention of AiOS is to improve and enhance the sidebar handling and the related built-in features of Firefox itself. AiOS is not an extension for a lot of new sidebar panels like tab lists, notes, rss reader, instant messenger, social bookmark services, browsing sessions and so on.

**Comment by blausand** [comment]
ACK.
From the user perspective, however, i'd prefer not to have several sidebars at one time.
I really wonder why vertical tabs have still not arrived in the core as a native UI option, since we all migrated to 16:9 one zillion years ago.
Keep up good work, Ingo!
