### ISSUE TITLE
delicious bookmarking

### ISSUE THREAD

**Issue by brambix** [AddonLab/AiOS#98]
With the last version (0.2.28) i cannot sign in Delicious anymore. The" Sign in again" link point to blank page https://previous.delicious.com/login?src=ffbmext2.1.106&partner=ffbmext

**Comment by Dreadaxe** [comment]
+1

**Comment by ingowennemaring** [comment]
I can't reproduce the problem. But even if I could, this would be a problem of delicious.com and not of my extension.
